{
	"id": "CVE-2021-20217",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2021-20217",
				"description": "A flaw was found in Privoxy in versions before 3.0.31. An assertion failure triggered by a crafted CGI request may lead to denial of service. The highest threat from this vulnerability is to system availability.",
				"cwe": [
					{
						"source": "redhat",
						"cwe": [
							"CWE-617"
						]
					}
				],
				"references": [
					{
						"source": "CVE",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1923252"
					},
					{
						"source": "CVE",
						"url": "https://security.gentoo.org/glsa/202107-16"
					},
					{
						"source": "redhat",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1923252"
					},
					{
						"source": "redhat",
						"url": "https://security.gentoo.org/glsa/202107-16"
					}
				],
				"modified": "2024-08-03T17:30:07.475Z"
			}
		}
	],
	"data_source": {
		"id": "mitre-v5",
		"raws": [
			"vuls-data-raw-mitre-v5/2021/CVE-2021-20217.json"
		]
	}
}
