{
	"id": "CVE-2023-23931",
	"vulnerabilities": [
		{
			"id": "CVE-2023-23931",
			"title": "Cipher.update_into can corrupt memory in pyca cryptography",
			"description": "cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. In affected versions `Cipher.update_into` would accept Python objects which implement the buffer protocol, but provide only immutable buffers. This would allow immutable objects (such as `bytes`) to be mutated, thus violating fundamental rules of Python and resulting in corrupted output. This now correctly raises an exception. This issue has been present since `update_into` was originally introduced in cryptography 1.8.",
			"severity": [
				{
					"type": "cvss_v31",
					"source": "GitHub_M",
					"cvss_v31": {
						"vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:L",
						"base_score": 4.8,
						"base_severity": "MEDIUM",
						"temporal_score": 4.8,
						"temporal_severity": "MEDIUM",
						"environmental_score": 4.8,
						"environmental_severity": "MEDIUM"
					}
				}
			],
			"cwe": [
				{
					"source": "GitHub_M",
					"cwe": [
						"CWE-754"
					]
				}
			],
			"references": [
				{
					"source": "GitHub_M",
					"url": "https://github.com/pyca/cryptography/pull/8230/commits/94a50a9731f35405f0357fa5f3b177d46a726ab3"
				},
				{
					"source": "GitHub_M",
					"url": "https://github.com/pyca/cryptography/security/advisories/GHSA-w7pp-m8wf-vj6r"
				}
			],
			"published": "2023-02-07T20:54:03.628Z"
		}
	],
	"data_source": "mitre-v5"
}
