{
	"id": "CVE-2020-35518",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2020-35518",
				"description": "When binding against a DN during authentication, the reply from 389-ds-base will be different whether the DN exists or not. This can be used by an unauthenticated attacker to check the existence of an entry in the LDAP database.",
				"cwe": [
					{
						"source": "redhat",
						"cwe": [
							"CWE-200"
						]
					}
				],
				"references": [
					{
						"source": "CVE",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1905565"
					},
					{
						"source": "CVE",
						"url": "https://github.com/389ds/389-ds-base/commit/b6aae4d8e7c8a6ddd21646f94fef1bf7f22c3f32"
					},
					{
						"source": "CVE",
						"url": "https://github.com/389ds/389-ds-base/commit/cc0f69283abc082488824702dae485b8eae938bc"
					},
					{
						"source": "CVE",
						"url": "https://github.com/389ds/389-ds-base/issues/4480"
					},
					{
						"source": "redhat",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1905565"
					},
					{
						"source": "redhat",
						"url": "https://github.com/389ds/389-ds-base/commit/b6aae4d8e7c8a6ddd21646f94fef1bf7f22c3f32"
					},
					{
						"source": "redhat",
						"url": "https://github.com/389ds/389-ds-base/commit/cc0f69283abc082488824702dae485b8eae938bc"
					},
					{
						"source": "redhat",
						"url": "https://github.com/389ds/389-ds-base/issues/4480"
					}
				],
				"modified": "2024-08-04T17:02:08.248Z"
			}
		}
	],
	"data_source": {
		"id": "mitre-v5",
		"raws": [
			"vuls-data-raw-mitre-v5/2020/CVE-2020-35518.json"
		]
	}
}
