{
	"id": "CVE-2020-24119",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2020-24119",
				"description": "A heap buffer overflow read was discovered in upx 4.0.0, because the check in p_lx_elf.cpp is not perfect.",
				"references": [
					{
						"source": "CVE",
						"url": "https://cwe.mitre.org/data/definitions/126.html"
					},
					{
						"source": "CVE",
						"url": "https://github.com/upx/upx/issues/388"
					},
					{
						"source": "CVE",
						"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JE54WKVU7MATB4WZD3MJFBAHFRJ3NTQX/"
					},
					{
						"source": "CVE",
						"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VSQRO7YC72PSYDQG4PQLQYXZTZE3B4YV/"
					},
					{
						"source": "mitre",
						"url": "https://cwe.mitre.org/data/definitions/126.html"
					},
					{
						"source": "mitre",
						"url": "https://github.com/upx/upx/issues/388"
					},
					{
						"source": "mitre",
						"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JE54WKVU7MATB4WZD3MJFBAHFRJ3NTQX/"
					},
					{
						"source": "mitre",
						"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VSQRO7YC72PSYDQG4PQLQYXZTZE3B4YV/"
					}
				],
				"modified": "2024-08-04T15:05:11.907Z"
			}
		}
	],
	"data_source": {
		"id": "mitre-v5",
		"raws": [
			"vuls-data-raw-mitre-v5/2020/CVE-2020-24119.json"
		]
	}
}
