{
	"id": "CVE-2020-4642",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2020-4642",
				"description": "IBM DB2 for Linux, UNIX and Windows (includes DB2 Connect Server) 9.7, 10.1, 10.5, 11.1, and 11.5 could allow local attacker to cause a denial of service inside the \"DB2 Management Service\".",
				"severity": [
					{
						"type": "cvss_v30",
						"source": "ibm",
						"cvss_v30": {
							"vector": "CVSS:3.0/S:U/C:N/UI:N/PR:N/I:N/AV:L/AC:L/A:H/RC:C/E:U/RL:O",
							"base_score": 6.2,
							"base_severity": "MEDIUM",
							"temporal_score": 5.4,
							"temporal_severity": "MEDIUM",
							"environmental_score": 5.4,
							"environmental_severity": "MEDIUM"
						}
					}
				],
				"references": [
					{
						"source": "CVE",
						"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/185589"
					},
					{
						"source": "CVE",
						"url": "https://security.netapp.com/advisory/ntap-20210129-0009/"
					},
					{
						"source": "CVE",
						"url": "https://www.ibm.com/support/pages/node/6391652"
					},
					{
						"source": "ibm",
						"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/185589"
					},
					{
						"source": "ibm",
						"url": "https://security.netapp.com/advisory/ntap-20210129-0009/"
					},
					{
						"source": "ibm",
						"url": "https://www.ibm.com/support/pages/node/6391652"
					}
				],
				"modified": "2024-08-04T08:07:49.116Z"
			}
		}
	],
	"data_source": {
		"id": "mitre-v5",
		"raws": [
			"vuls-data-raw-mitre-v5/2020/CVE-2020-4642.json"
		]
	}
}
