{
	"id": "CVE-2010-3494",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2010-3494",
				"description": "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.2 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, a related issue to CVE-2010-3492.",
				"references": [
					{
						"source": "CVE",
						"url": "http://bugs.python.org/issue6706"
					},
					{
						"source": "CVE",
						"url": "http://code.google.com/p/pyftpdlib/issues/detail?id=104"
					},
					{
						"source": "CVE",
						"url": "http://code.google.com/p/pyftpdlib/issues/detail?id=105"
					},
					{
						"source": "CVE",
						"url": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY"
					},
					{
						"source": "CVE",
						"url": "http://code.google.com/p/pyftpdlib/source/detail?r=556"
					},
					{
						"source": "CVE",
						"url": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn556&r=556&format=side&path=/trunk/pyftpdlib/ftpserver.py"
					},
					{
						"source": "CVE",
						"url": "http://www.openwall.com/lists/oss-security/2010/09/09/6"
					},
					{
						"source": "CVE",
						"url": "http://www.openwall.com/lists/oss-security/2010/09/11/2"
					},
					{
						"source": "CVE",
						"url": "http://www.openwall.com/lists/oss-security/2010/09/22/3"
					},
					{
						"source": "CVE",
						"url": "http://www.openwall.com/lists/oss-security/2010/09/24/3"
					},
					{
						"source": "CVE",
						"url": "https://bugs.launchpad.net/zodb/+bug/135108"
					},
					{
						"source": "mitre",
						"url": "http://bugs.python.org/issue6706"
					},
					{
						"source": "mitre",
						"url": "http://code.google.com/p/pyftpdlib/issues/detail?id=104"
					},
					{
						"source": "mitre",
						"url": "http://code.google.com/p/pyftpdlib/issues/detail?id=105"
					},
					{
						"source": "mitre",
						"url": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY"
					},
					{
						"source": "mitre",
						"url": "http://code.google.com/p/pyftpdlib/source/detail?r=556"
					},
					{
						"source": "mitre",
						"url": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn556&r=556&format=side&path=/trunk/pyftpdlib/ftpserver.py"
					},
					{
						"source": "mitre",
						"url": "http://www.openwall.com/lists/oss-security/2010/09/09/6"
					},
					{
						"source": "mitre",
						"url": "http://www.openwall.com/lists/oss-security/2010/09/11/2"
					},
					{
						"source": "mitre",
						"url": "http://www.openwall.com/lists/oss-security/2010/09/22/3"
					},
					{
						"source": "mitre",
						"url": "http://www.openwall.com/lists/oss-security/2010/09/24/3"
					},
					{
						"source": "mitre",
						"url": "https://bugs.launchpad.net/zodb/+bug/135108"
					}
				],
				"modified": "2024-08-07T03:11:44.302Z"
			}
		}
	],
	"data_source": "mitre-v5"
}
