{
	"id": "CVE-2018-11499",
	"vulnerabilities": [
		{
			"id": "CVE-2018-11499",
			"description": "A use-after-free vulnerability exists in handle_error() in sass_context.cpp in LibSass 3.4.x and 3.5.x through 3.5.4 that could be leveraged to cause a denial of service (application crash) or possibly unspecified other impact.",
			"references": [
				{
					"source": "mitre",
					"url": "http://lists.opensuse.org/opensuse-security-announce/2019-07/msg00047.html"
				},
				{
					"source": "mitre",
					"url": "http://lists.opensuse.org/opensuse-security-announce/2019-07/msg00051.html"
				},
				{
					"source": "mitre",
					"url": "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00027.html"
				},
				{
					"source": "mitre",
					"url": "https://github.com/sass/libsass/issues/2643"
				}
			]
		}
	],
	"data_source": "mitre-v5"
}
