{
	"id": "CVE-2019-14859",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2019-14859",
				"description": "A flaw was found in all python-ecdsa versions before 0.13.3, where it did not correctly verify whether signatures used DER encoding. Without this verification, a malformed signature could be accepted, making the signature malleable. Without proper verification, an attacker could use a malleable signature to create false transactions.",
				"severity": [
					{
						"type": "cvss_v30",
						"source": "redhat",
						"cvss_v30": {
							"vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
							"base_score": 7.4,
							"base_severity": "HIGH",
							"temporal_score": 7.4,
							"temporal_severity": "HIGH",
							"environmental_score": 7.4,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "redhat",
						"cwe": [
							"CWE-347"
						]
					}
				],
				"references": [
					{
						"source": "CVE",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14859"
					},
					{
						"source": "CVE",
						"url": "https://github.com/warner/python-ecdsa/issues/114"
					},
					{
						"source": "CVE",
						"url": "https://github.com/warner/python-ecdsa/releases/tag/python-ecdsa-0.13.3"
					},
					{
						"source": "CVE",
						"url": "https://pypi.org/project/ecdsa/0.13.3/"
					},
					{
						"source": "redhat",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14859"
					},
					{
						"source": "redhat",
						"url": "https://github.com/warner/python-ecdsa/issues/114"
					},
					{
						"source": "redhat",
						"url": "https://github.com/warner/python-ecdsa/releases/tag/python-ecdsa-0.13.3"
					},
					{
						"source": "redhat",
						"url": "https://pypi.org/project/ecdsa/0.13.3/"
					}
				],
				"modified": "2024-08-05T00:26:39.127Z"
			}
		}
	],
	"data_source": {
		"id": "mitre-v5",
		"raws": [
			"vuls-data-raw-mitre-v5/2019/CVE-2019-14859.json"
		]
	}
}
