{
	"id": "CVE-2022-22846",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2022-22846",
				"description": "The dnslib package through 0.9.16 for Python does not verify that the ID value in a DNS reply matches an ID value in a query.",
				"severity": [
					{
						"type": "cvss_v31",
						"source": "mitre",
						"cvss_v31": {
							"vector": "CVSS:3.1/AC:L/AV:N/A:N/C:N/I:H/PR:N/S:U/UI:N",
							"base_score": 7.5,
							"base_severity": "HIGH",
							"temporal_score": 7.5,
							"temporal_severity": "HIGH",
							"environmental_score": 7.5,
							"environmental_severity": "HIGH"
						}
					}
				],
				"references": [
					{
						"source": "CVE",
						"url": "https://github.com/paulc/dnslib/issues/30"
					},
					{
						"source": "mitre",
						"url": "https://github.com/paulc/dnslib/issues/30"
					}
				],
				"modified": "2024-08-03T03:28:42.473Z"
			}
		}
	],
	"data_source": {
		"id": "mitre-v5",
		"raws": [
			"vuls-data-raw-mitre-v5/2022/CVE-2022-22846.json"
		]
	}
}
