{
	"id": "CVE-2022-36126",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2022-36126",
				"description": "An issue was discovered in Inductive Automation Ignition before 7.9.20 and 8.x before 8.1.17. The ScriptInvoke function allows remote attackers to execute arbitrary code by supplying a Python script.",
				"severity": [
					{
						"type": "cvss_v31",
						"source": "mitre",
						"cvss_v31": {
							"vector": "CVSS:3.1/AC:L/AV:N/A:H/C:H/I:H/PR:H/S:U/UI:N",
							"base_score": 7.2,
							"base_severity": "HIGH",
							"temporal_score": 7.2,
							"temporal_severity": "HIGH",
							"environmental_score": 7.2,
							"environmental_severity": "HIGH"
						}
					}
				],
				"references": [
					{
						"source": "CVE",
						"url": "https://github.com/sourceincite/randy"
					},
					{
						"source": "CVE",
						"url": "https://srcincite.io/advisories/src-2022-0014/"
					},
					{
						"source": "CVE",
						"url": "https://support.inductiveautomation.com/hc/en-us/articles/7625759776653"
					},
					{
						"source": "mitre",
						"url": "https://github.com/sourceincite/randy"
					},
					{
						"source": "mitre",
						"url": "https://srcincite.io/advisories/src-2022-0014/"
					},
					{
						"source": "mitre",
						"url": "https://support.inductiveautomation.com/hc/en-us/articles/7625759776653"
					}
				],
				"modified": "2024-08-03T10:00:01.571Z"
			}
		}
	],
	"data_source": {
		"id": "mitre-v5",
		"raws": [
			"vuls-data-raw-mitre-v5/2022/CVE-2022-36126.json"
		]
	}
}
