{
	"id": "CVE-2022-30877",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2022-30877",
				"description": "The keep for python, as distributed on PyPI, included a code-execution backdoor inserted by a third party. The current version, without this backdoor, is 1.2.",
				"references": [
					{
						"source": "CVE",
						"url": "http://pypi.doubanio.com/simple/request"
					},
					{
						"source": "CVE",
						"url": "https://github.com/OrkoHunter/keep/issues/85"
					},
					{
						"source": "CVE",
						"url": "https://pypi.org/project/keep"
					},
					{
						"source": "mitre",
						"url": "http://pypi.doubanio.com/simple/request"
					},
					{
						"source": "mitre",
						"url": "https://github.com/OrkoHunter/keep/issues/85"
					},
					{
						"source": "mitre",
						"url": "https://pypi.org/project/keep"
					}
				],
				"modified": "2024-08-03T07:03:40.158Z"
			}
		}
	],
	"data_source": {
		"id": "mitre-v5",
		"raws": [
			"vuls-data-raw-mitre-v5/2022/CVE-2022-30877.json"
		]
	}
}
